### ISSUE TITLE
Videos with .webm format won't play

### ISSUE THREAD

**Issue by JeysRT** [montoyo/webdisplays#106]
I know about the problem that WD can't play videos with H.256/H.264 codecs wich are used by .mkv .mp4 ... I converted a movie to webm with the vp8 video codec and vorbis audio. Then after uploading the movie to the wd filehost, it didn't started playing. I also tried to upload it into the Server-Global host and i didn't work aswell.

**Comment by ItsK1tty** [comment]
Can you send me the video you're trying to play?

**Comment by mishal321** [comment]
> I know about the problem that WD can't play videos with H.256/H.264 codecs wich are used by .mkv .mp4 ... I converted a movie to webm with the vp8 video codec and vorbis audio. Then after uploading the movie to the wd filehost, it didn't started playing. I also tried to upload it into the Server-Global host and i didn't work aswell.

How did you even get the mp4 to work? I have tried everything, nothing worked.

**Comment by JeysRT** [comment]
Mp4 doesn't work at all because it's using the H.264/256 decoder

**Comment by ItsK1tty** [comment]
this, and there were no updates for just 2 years

**Comment by JeysRT** [comment]
Yeah, i think montoyo has no time to update or it is difficult update cef. I dont know much about chromium

**Comment by mishal321** [comment]
> Yeah, i think montoyo has no time to update or it is difficult update cef. I dont know much about chromium

Quick question, has it even worked for you? Like have you tried mkv, and did it work?

**Comment by JeysRT** [comment]
No, as i said .mp4,.mkv,... Are using H.264/256 codecs, what means it dont work.

**Comment by JeysRT** [comment]
The only thing you can do is:

- convert a video to .webm with
  - VP8/9 video codec
  - opus/vorbis audio codex

- upload it on a webserver where you can get a direct link to the video.

And don't even try to use miniServ to play the video, it won't work

**Comment by ItsK1tty** [comment]
> > Yeah, i think montoyo has no time to update or it is difficult update cef. I dont know much about chromium
> 
> Quick question, has it even worked for you? Like have you tried mkv, and did it work?
> 

it's not about container or a format. Inside the audio file, there're two streams: audio stream and video stream. They're encoded using some codec usually aac and avc). you can check what codecs does WD support at https://html5test.com, and you will clearly see that the only options are VP8 & VP9 for video stream and Opus & Vorbis for audio stream. Personally, I use [handbrake](https://handbrake.fr) to transcode video files, but you need some computer power to encode videos with the same quality as it was before transcoding. Beware that Handbrake mainly uses CPU, not GPU. I overclocked my CPU to 5GHz because of that, and it increases the performance by somewhere of 50%, and since I'm not transcoding anything anymore, I can do it for you, just give me a file

**Comment by JeysRT** [comment]
My movie took 7hours to encode. This was a mess.

**Comment by ItsK1tty** [comment]
that's what it takes to watch anime in minecraft...
