### ISSUE TITLE
Sound levels

### ISSUE THREAD

**Issue by shufunk** [montoyo/webdisplays#3]
This is more of a request then an actual issue.

I like the idea there is an option to have the volume lower as you get further away from the screen but how about an option to change the distance?  Forgive me that i didn't actual get the actual distance in this video but if you watch it you see what i mean when it's weird hearing the video outside of a theater.

https://www.youtube.com/watch?v=5zQdnpegyIE

I am aware there is the sound muffler from Extra Utilities 2 and two other mods that mute sounds but neither one works.

**Comment by montoyo** [comment]
Hello,
Thanks for your suggestion. I'll add a config option to change the volume/distance ratio of YouTube videos.
The sound muffler from EU2 doesn't work because the MCEF uses a completely different sound system (which has nothing to do with Minecraft) and I'm afraid I have no control over it. YouTube is an exception because its quite easy to change the volume using JavaScript.

Anyway, I'll definitely add this to the next WebDisplays version.

**Comment by montoyo** [comment]
Alright. Added two options (dist100 and dist0) in the configuration file to control the sound/distance effect. Will be available in the next update, which should come in the next few days.
