### ISSUE TITLE
everyone sees the video different?

### ISSUE THREAD

**Issue by Joshuam303** [montoyo/webdisplays#38]
Hi! for some reason when we were watching tv (with the mod) when 1 person paused it didn't pause for everyone just half?

**Comment by ItsK1tty** [comment]
In Multiplayer, screens ARE NOT fully synchronized. Every player has a separate web browser instance, and may not see web pages the same way. Most of the time web pages do not change depending on who's watching them; in this case Screens look synchronized. However, the YouTube homepage, for instance, suggests videos based on your video history (among other things). So if a player clicks on a video on the YouTube homepage, everyone may see a different video depending on what YouTube suggested (that's why you should always copy/paste the URL if you want to display a specific video).
https://montoyo.net/wdwiki/index.php/Screen#Multiplayer_synchronization
