### ISSUE TITLE
Sync [suggestion]

### ISSUE THREAD

**Issue by ItsK1tty** [montoyo/webdisplays#44]
So, my suggestion is simple (or maybe not):
Make a sync between players, so everyone could've see same youtube recommendations, etc. I've drown a principle of operation
https://i.imgur.com/SVQtQfr.png

**Comment by montoyo** [comment]
If the lines between the server and player a, b, and c means "stream" then it would just kill the server's bandwidth. Also most of servers don't have what's required to render web pages.

If it means "send the page source", it means that I would have to modify chromium and make it so that every requests go through the Minecraft server. Besides modifying chromium being a pain in the ass, it would cause tons of security issues. The most obvious one being that any player on the server could divert the mod to send DDOS attacks or use it as a kind of VPN to buy illegal stuff.

**Comment by ItsK1tty** [comment]
Hm, we can make a hosts file for the server, so it can prevent users to browse blacklisted websites

**Comment by ItsK1tty** [comment]
If everything you say is true, I don't see any other way to make a sync for all players

**Comment by JeysRT** [comment]
What if it synchronizes with 1 player. The one who created the WebDisplay is the owner for example and the other players can see the same thing as the owner. (Sorry my English is bad if you don't understand)

**Comment by ItsK1tty** [comment]
nice thought, but what if the screen owner is offline?

**Comment by JeysRT** [comment]
you, could make an item to change the owner maybe.

**Comment by LETHALKRILL** [comment]
After 6 years, is this ever going to be implemented? I really want to watch youtube with friends on my server

**Comment by NRVT76** [comment]
> After 6 years, is this ever going to be implemented? I really want to watch youtube with friends on my server

For that, I would recommend WaterMedia and WaterFrames, which adds televisions/projectors you can put YouTube Links on, syncs, has pausing, fast-forwarding, no ads, and other convenient options. It has worked well for me so far.

I do wish it synced though, since other players can't watch if I played a browser game.

**Comment by PunkyPup** [comment]
WaterFrames have way worse quality of picture so uhh... it would be cool if it worked like WebDisplays, bcz it looks better
